name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # 根据项目需求选择 Node.js 版本

      # 安装依赖
      - name: Install dependencies
        run: yarn install

      # 构建项目
      - name: Build
        env:
          BASE_PATH: /LOVE20-interface
          ASSET_PREFIX: /LOVE20-interface
          NEXT_PUBLIC_CHAIN: thinkium801
          NEXT_PUBLIC_BLOCK_TIME: 3
          NEXT_PUBLIC_SEPOLIA_RPC_URL: https://eth-sepolia.g.alchemy.com/v2/lbm2CtlP-tYuSEpPr8k0QhvFLqrXX9em
          NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID: 3e08c0ee570fce9c29473eb34b0532c3
          NEXT_PUBLIC_FOUNDRY_CORE_ABI_PATH: ../LOVE20-core/out/
          NEXT_PUBLIC_FOUNDRY_PERIPHERAL_ABI_PATH: ../LOVE20-peripheral/out/
          NEXT_PUBLIC_BASE_PATH: /LOVE20-interface

          NEXT_PUBLIC_FIRST_TOKEN_NAME: TEST20
          NEXT_PUBLIC_FIRST_TOKEN_SYMBOL: TEST20
          NEXT_PUBLIC_FIRST_PARENT_TOKEN_SYMBOL: TestTKM20
          NEXT_PUBLIC_TOKEN_DECIMALS: 18
          NEXT_PUBLIC_FIRST_PARENT_TOKEN_FUNDRAISING_GOAL: '100000000000000000'
          NEXT_PUBLIC_PARENT_TOKEN_FUNDRAISING_GOAL: '20000000000000000000000000'
          NEXT_PUBLIC_LAUNCH_AMOUNT: '1000000000000000000000000000'
          NEXT_PUBLIC_WITHDRAW_WAITING_BLOCKS: 400
          NEXT_PUBLIC_PHASE_BLOCKS: 100
          NEXT_PUBLIC_JOIN_END_ROUND_BLOCKS: 1
          NEXT_PUBLIC_SUBMIT_MIN_PER_THOUSAND: 5

          NEXT_PUBLIC_CONTRACT_ADDRESS_FEE_TO_SETTER:
          NEXT_PUBLIC_CONTRACT_ADDRESS_ROOT_PARENT_TOKEN: '0x36398C7CC57fE37dff6f8CB5678DB51D72e57801'
          NEXT_PUBLIC_CONTRACT_ADDRESS_UNISWAP_V2_FACTORY: '0x1Af34722155d25d57012Ecc4DB88f1404A8162B6'
          NEXT_PUBLIC_CONTRACT_ADDRESS_TOKEN_FACTORY: '0xee91A3Df31E5EB0e028755a42299438142a20C3F'
          NEXT_PUBLIC_CONTRACT_ADDRESS_LAUNCH: '0xA1B7473fB00aA6F686Db227E2b7F0c4abd588387'
          NEXT_PUBLIC_CONTRACT_ADDRESS_STAKE: '0xf97F529C97E02Ec63CAb27142FEbA5a0A1bC7b25'
          NEXT_PUBLIC_CONTRACT_ADDRESS_SUBMIT: '0x35692C6C43D9cF75e87Ef8E41a8A95D1441bF754'
          NEXT_PUBLIC_CONTRACT_ADDRESS_VOTE: '0xBe13F2FaCB9b3F959deAA27998dD100d1DBCEd3C'
          NEXT_PUBLIC_CONTRACT_ADDRESS_JOIN: '0x738536dA6B704fD66742d5CF9025A5F50b69291e'
          NEXT_PUBLIC_CONTRACT_ADDRESS_RANDOM: '0xB8Fa9C3ef400ffACb5eF4622F9F12E3233fceb6e'
          NEXT_PUBLIC_CONTRACT_ADDRESS_VERIFY: '0x1F8EE7A1e950e1CDfBBc878cDA0cFAC5da08a31A'
          NEXT_PUBLIC_CONTRACT_ADDRESS_MINT: '0xd954067e5Fff7F9275b362Ce2074433b755D4029'

          NEXT_PUBLIC_CONTRACT_ADDRESS_FIRST_TOKEN: '0x5170b8de14cE4EBdC6B24942A75c8B7948F2D05c'
          NEXT_PUBLIC_CONTRACT_ADDRESS_FIRST_SL_TOKEN: '0xB862c1c72Ec0aC5d564c0739E90910CC168A2328'
          NEXT_PUBLIC_CONTRACT_ADDRESS_FIRST_ST_TOKEN: '0x14B19f9ee14A9481901b4a30505112b0D059b5f2'

          NEXT_PUBLIC_CONTRACT_ADDRESS_PERIPHERAL_DATAVIEWER: '0x83A7a8E36728f020844930f4cb690e4f98125116'
          NEXT_PUBLIC_CONTRACT_ADDRESS_UNISWAP_V2_ROUTER: '0x14Bf22401Ec678dFC3972A4e535486b395213d6c'

          # 添加其他环境变量，如果有的话
        run: |
          yarn build
          cp out/index.html out/404.html

      # 检查静态文件
      - name: List build files
        run: ls -R out/

      # 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          # 如果需要自定义域名，可以添加以下内容
          # cname: your-custom-domain.com
